### ISSUE TITLE
No boot

### ISSUE THREAD

**Issue by FlaggShot** [Ch4r0ne/ARK-Ascended-Server-Manager#24]
After the install, when I press the "Start Server" button I get the message "ARK Server has been started successful" instantly but the server never starts

**Comment by Pitbully01** [comment]
are you on the latest version?
and is it up to date via the update button?

**Comment by Ch4r0ne** [comment]
@FlaggShot Unfortunately, this can still happen, thank you for pointing out a bug. check whether the installation has taken place on the folder structures. I think you have executed the installation with too few rights.

Only for the installation and to create Jobs Admin rights are necessary, once this is installed you should have no problems with the server start.

**Comment by FlaggShot** [comment]
> @FlaggShot Unfortunately, this can still happen, thank you for pointing out a bug. check whether the installation has taken place on the folder structures. I think you have executed the installation with too few rights.
> 
> Only for the installation and to create Jobs Admin rights are necessary, once this is installed you should have no problems with the server start.

I've tried updating with admin rights but that did not resolve the issue. I'll try a full reinstall with admin rights

**Comment by Ch4r0ne** [comment]
> > @FlaggShot Unfortunately, this can still happen, thank you for pointing out a bug. check whether the installation has taken place on the folder structures. I think you have executed the installation with too few rights.
> > Only for the installation and to create Jobs Admin rights are necessary, once this is installed you should have no problems with the server start.
> 
> I've tried updating with admin rights but that did not resolve the issue. I'll try a full reinstall with admin rights

could a reinstallation solve your problem, if not we can also exchange ideas via Discord and I will help you with the solution

**Comment by Ch4r0ne** [comment]
Unfortunately no further feedback, as I have not received any further reports of such errors, I hereby close the case. Important: Admin rights are required to install or add tasks. To start the server later, none are required after the installation, only for the initial setup
