### ISSUE TITLE
Server Wont Update

### ISSUE THREAD

**Issue by Tag56** [Ch4r0ne/ARK-Ascended-Server-Manager#27]
Have not been able to get the server to update. Im stuck on V26.11. Not sure how to force it to install the new update? Should be able to be on 26.38.

**Comment by Ch4r0ne** [comment]
I'm not aware of any problems with this yet, actually the latest update must be downloaded directly during installation. Otherwise there is a problem with the Steam database. 

@Pejyuu Many thanks for your contribution

**Comment by Ch4r0ne** [comment]
Tested, currently there is no problem with the updates, Steam may have withdrawn a newer version for a short time and rolled it out again later
