### ISSUE TITLE
Populating unneeded configs

### ISSUE THREAD

**Issue by Pejyuu** [Ch4r0ne/ARK-Ascended-Server-Manager#29]
Hello! 
Is there a reason for the configs to be auto-populated with a lot of unneeded information like graphics and audio-related whenever I start the server? 
I would like as clean configs as possible, only overwriting game defaults with the configs. 

Thank you :)

**Comment by J-eremy** [comment]
> Hello! Is there a reason for the configs to be auto-populated with a lot of unneeded information like graphics and audio-related whenever I start the server? I would like as clean configs as possible, only overwriting game defaults with the configs.
> 
> Thank you :)

The server itself does this on its own. This is not a problem with the script. I'm not sure why they chose to have the config write itself out at every launch and close but they did. What I did was get the config the way I wanted it and make the file read only. On windows you just right click the file and check the read only box.

This script appears to check if there are the Game.ini and GameUserSettings.ini configs located where they are supposed to be, and if not writes the default values into them. If they exist it does nothing. What this script is really doing is building the launch command for the server itself, and not modifying any configs. It reads the config files mainly for displaying the current settings in the UI itself.

**Comment by Ch4r0ne** [comment]
Short addition, the Game.ini is created on the default values, but only if they do not already exist.

@J-eremy Thank you for your explanation
