### ISSUE TITLE
Response: Authentication failed!

### ISSUE THREAD

**Issue by ASHPR18** [Ch4r0ne/ARK-Ascended-Server-Manager#36]
Ive setup everything port forwarded etc, and have been able to join the server.

However i cannot use any rcon commands like savegame, stop server etc... why is this?

![image](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/85460939/c0390cab-cf82-446c-aeff-8c5707d8fba6)

**Comment by ASHPR18** [comment]
if i do not respond to this could you please send me a message on discord : ashpr

**Comment by Ch4r0ne** [comment]
Discord ch4r0ne =)

we can look at this together, but I think the admin password was transferred incorrectly in the GameUserSettings.ini please check the entry "ServerAdminPassword="

**Comment by Ch4r0ne** [comment]
as just written special characters were the problem, I close the issue
