### ISSUE TITLE
[Request] Direct link to your cert install script here

### ISSUE THREAD

**Issue by Bryantdl7** [Ch4r0ne/ARK-Ascended-Server-Manager#43]
Can you make a file here for the powershell script you made over on https://www.reddit.com/r/ARK/comments/17ljd4g/ark_survival_ascended_dedicated_server_list_issue/ ? 

For people who run other hosting solutions, in my case cubecoders' AMP I just need the certificate installer (allegedly) and I am now good to go.

**Comment by Ch4r0ne** [comment]
@Bryantdl7 I have a new repository for you and explain the installation.
[](https://github.com/Ch4r0ne/UnrealEngine_Dedicated_Server_Install_CA/tree/main)

Install Certificate Skirpt in Powershell:
[](https://github.com/Ch4r0ne/UnrealEngine_Dedicated_Server_Install_CA/blob/main/Install_Certificate.ps1)

I would be happy about a star =)
