### ISSUE TITLE
Server not showing in Server list

### ISSUE THREAD

**Issue by akorb90** [Ch4r0ne/ARK-Ascended-Server-Manager#47]
I installed an instance with the script.

I can connect and play on it when using the console.

It's not showing in the server listt though.

Cert and CRL are installed. Any idea?

**Comment by Ch4r0ne** [comment]
Please check your router for the correct port forwarding

**Comment by akorb90** [comment]
No port forwarding, server got a public ip itself and is reachable.

For testing I added an any to any rule on the fw, didn't change anything on the issue.

**Comment by Ch4r0ne** [comment]
Please check the guideline and send me the result

https://github.com/Ch4r0ne/UnrealEngine_Dedicated_Server_Install_CA

**Comment by Ch4r0ne** [comment]
@akorb90 Were you able to solve the problem and do you need further support?

**Comment by akorb90** [comment]
Hi,
unfortunately not:
![image](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/61040288/57ed07b7-074d-4f24-83a7-95f7a408555f)
![image](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/61040288/0125184c-242e-4aff-af59-8f535867f7d3)
![image](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/61040288/da4e7d4a-335f-4d53-bc12-1e60d95b4e12)
![image](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/61040288/1809d82a-d4e6-4df2-9501-a9926153d6cc)

netstat shows the following connections for the ASA process:
 TCP    0.0.0.0:27020          0.0.0.0:0              LISTENING       8384
  TCP    PublicIPofServer:55160   35.171.131.137:443     ESTABLISHED     8384
  TCP    PublicIPofServer:55166   108.138.26.44:443      CLOSE_WAIT      8384
TCP    127.0.0.1:8888         0.0.0.0:0              LISTENING       8384
  UDP    0.0.0.0:7777           *:*                                    8384

The IPs 35.171.131.137 and 108.138.26.44 are from Amazon/AWS.

Any more Ideas?

**Comment by Ch4r0ne** [comment]
Please delete all Amazon certificates again, somehow this does not work for you. Initially it must look like this:
![grafik](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/54702161/2ea19b16-db77-4c09-be45-ccabb4e26775)

After run https://github.com/Ch4r0ne/UnrealEngine_Dedicated_Server_Install_CA/blob/main/Install_Certificate.ps1 3 CAs are installed.

![grafik](https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/assets/54702161/8726d713-c470-4102-b917-5a6a2e8c02f2)

**Comment by akorb90** [comment]
So I have just set up another instance on a server system in my homelab.
Portforwarding working just fine, server is running, can play on it, but it doesn't get listed...I don't know...

**Comment by Ch4r0ne** [comment]
I can check after work today whether this is listed for me when I reinstall the server on a VM.  

I will come back to you with the results.

This will show us whether this is a general problem or whether something has changed in the certification.

**Comment by Ch4r0ne** [comment]
I have executed the script with admin rights on a completely new Win11 client, entered the data and clicked on Install https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/blob/main/ARK-Ascended-Server-Manager.ps1 

This installed the server, then quickly set the port forwarding rule 

WAN UDP * * WAN address 27020 10.0.0.161 27020 Ark ASA 

Server Started after installation with the buttons and it was there, make sure you use a simple name if necessary. In Ark ASA you will find your server on Unofficial and with the check mark Password protected server as well as Show player server.

Unfortunately I can't find any problem, it works exactly as it should.

**Comment by akorb90** [comment]
Thanks for trying!

Which OS did you use? Maybe it's an issue with server 2022.

I will try different ones tomorrow.

**Comment by Ch4r0ne** [comment]
The only difference between windows 10 / 11 and server 2022 is that windows 10 / 11 gives a notification when the firewall blocks a newly installed program. With windows Server you have to set the notification manually and you don't get a hint.

**Comment by akorb90** [comment]
I turned firewall off for testing on the system with the directly assigned public ip. Checked the ports with nmap and they were open.

I can say for sure that it's not the fw.

**Comment by akorb90** [comment]
I got it working, the behaviour is like super weird.

I can find all the servers when ticking the box "show player servers", then entering a part of the server name and then hitting refresh.

So not an issue with the script at all! Thanks for the help, gonna dig depper on why this behaves like this.
