### ISSUE TITLE
Have It Broadcast tool?

### ISSUE THREAD

**Issue by Albertitoink98** [Ch4r0ne/ARK-Ascended-Server-Manager#6]
I want to know if this programa have rcon tool with Broadcast messages because i already tried many diferentes server mánagers and Broadcast messages not working in ark ascended with rcon tools

**Comment by Ch4r0ne** [comment]
Sure, no problem, I have added RCON feature: https://github.com/Ch4r0ne/ARK-Ascended-Server-Manager/releases/tag/1.0.6
